# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from yapper_rpc import asr_pb2 as yapper__rpc_dot_asr__pb2


class AsrStub(object):
    """WhisperX ASR service. Mirrors the former REST contract (asr_client.py): upload a
    16 kHz mono WAV, get back word-level segments (+ optional speaker labels).

    Transcribe is CLIENT-STREAMING because a feature-length film's WAV is hundreds of
    MB — far past gRPC's 4 MB default message size. The first message carries the
    config; every subsequent message is a chunk of the WAV bytes, in order.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.stream_unary(
                '/yapper_rpc.Asr/Transcribe',
                request_serializer=yapper__rpc_dot_asr__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=yapper__rpc_dot_asr__pb2.TranscriptReply.FromString,
                )


class AsrServicer(object):
    """WhisperX ASR service. Mirrors the former REST contract (asr_client.py): upload a
    16 kHz mono WAV, get back word-level segments (+ optional speaker labels).

    Transcribe is CLIENT-STREAMING because a feature-length film's WAV is hundreds of
    MB — far past gRPC's 4 MB default message size. The first message carries the
    config; every subsequent message is a chunk of the WAV bytes, in order.
    """

    def Transcribe(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AsrServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.stream_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=yapper__rpc_dot_asr__pb2.TranscribeRequest.FromString,
                    response_serializer=yapper__rpc_dot_asr__pb2.TranscriptReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yapper_rpc.Asr', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Asr(object):
    """WhisperX ASR service. Mirrors the former REST contract (asr_client.py): upload a
    16 kHz mono WAV, get back word-level segments (+ optional speaker labels).

    Transcribe is CLIENT-STREAMING because a feature-length film's WAV is hundreds of
    MB — far past gRPC's 4 MB default message size. The first message carries the
    config; every subsequent message is a chunk of the WAV bytes, in order.
    """

    @staticmethod
    def Transcribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/yapper_rpc.Asr/Transcribe',
            yapper__rpc_dot_asr__pb2.TranscribeRequest.SerializeToString,
            yapper__rpc_dot_asr__pb2.TranscriptReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
