# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yapper_rpc/asr.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14yapper_rpc/asr.proto\x12\nyapper_rpc\"a\n\x10TranscribeConfig\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x0f\n\x07\x64iarize\x18\x02 \x01(\x08\x12\x14\n\x0cmin_speakers\x18\x03 \x01(\x05\x12\x14\n\x0cmax_speakers\x18\x04 \x01(\x05\"e\n\x11TranscribeRequest\x12.\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x1c.yapper_rpc.TranscribeConfigH\x00\x12\x15\n\x0b\x61udio_chunk\x18\x02 \x01(\x0cH\x00\x42\t\n\x07payload\"R\n\x04Word\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\x01\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x01\x12\r\n\x05score\x18\x04 \x01(\x01\x12\x11\n\thas_score\x18\x05 \x01(\x08\"e\n\x07Segment\x12\r\n\x05start\x18\x01 \x01(\x01\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x01\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x0f\n\x07speaker\x18\x04 \x01(\t\x12\x1f\n\x05words\x18\x05 \x03(\x0b\x32\x10.yapper_rpc.Word\"J\n\x0fTranscriptReply\x12\x10\n\x08language\x18\x01 \x01(\t\x12%\n\x08segments\x18\x02 \x03(\x0b\x32\x13.yapper_rpc.Segment2Q\n\x03\x41sr\x12J\n\nTranscribe\x12\x1d.yapper_rpc.TranscribeRequest\x1a\x1b.yapper_rpc.TranscriptReply(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yapper_rpc.asr_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRANSCRIBECONFIG']._serialized_start=36
  _globals['_TRANSCRIBECONFIG']._serialized_end=133
  _globals['_TRANSCRIBEREQUEST']._serialized_start=135
  _globals['_TRANSCRIBEREQUEST']._serialized_end=236
  _globals['_WORD']._serialized_start=238
  _globals['_WORD']._serialized_end=320
  _globals['_SEGMENT']._serialized_start=322
  _globals['_SEGMENT']._serialized_end=423
  _globals['_TRANSCRIPTREPLY']._serialized_start=425
  _globals['_TRANSCRIPTREPLY']._serialized_end=499
  _globals['_ASR']._serialized_start=501
  _globals['_ASR']._serialized_end=582
# @@protoc_insertion_point(module_scope)
