# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from yapper_rpc import gpud_pb2 as yapper__rpc_dot_gpud__pb2


class GpudStub(object):
    """gpud — the on-demand GPU supervisor. Runs always-on (no model loaded) on the GPU box
    and owns a bounded pool of ASR/TTS model-server subprocesses. A worker leases an
    instance for the duration of one Celery task: gpud launches one on a GPU with free
    vRAM (or hands back a warm idle one), returns its address, and reaps it after an idle
    grace once released. Workers dial the returned `target` directly over gRPC (the model
    traffic never passes through gpud — it's control-plane only).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Acquire = channel.unary_unary(
                '/yapper_rpc.Gpud/Acquire',
                request_serializer=yapper__rpc_dot_gpud__pb2.AcquireRequest.SerializeToString,
                response_deserializer=yapper__rpc_dot_gpud__pb2.Lease.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/yapper_rpc.Gpud/Heartbeat',
                request_serializer=yapper__rpc_dot_gpud__pb2.LeaseRef.SerializeToString,
                response_deserializer=yapper__rpc_dot_gpud__pb2.HeartbeatReply.FromString,
                )
        self.Release = channel.unary_unary(
                '/yapper_rpc.Gpud/Release',
                request_serializer=yapper__rpc_dot_gpud__pb2.LeaseRef.SerializeToString,
                response_deserializer=yapper__rpc_dot_gpud__pb2.ReleaseReply.FromString,
                )
        self.Status = channel.unary_unary(
                '/yapper_rpc.Gpud/Status',
                request_serializer=yapper__rpc_dot_gpud__pb2.StatusRequest.SerializeToString,
                response_deserializer=yapper__rpc_dot_gpud__pb2.StatusReply.FromString,
                )


class GpudServicer(object):
    """gpud — the on-demand GPU supervisor. Runs always-on (no model loaded) on the GPU box
    and owns a bounded pool of ASR/TTS model-server subprocesses. A worker leases an
    instance for the duration of one Celery task: gpud launches one on a GPU with free
    vRAM (or hands back a warm idle one), returns its address, and reaps it after an idle
    grace once released. Workers dial the returned `target` directly over gRPC (the model
    traffic never passes through gpud — it's control-plane only).
    """

    def Acquire(self, request, context):
        """Ensure an instance of `service` is running and lease it exclusively. Blocks up to
        the server's acquire timeout when the pool is full / no GPU fits, then fails
        UNAVAILABLE so the caller can retry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Refresh a lease's TTL so the instance isn't reclaimed mid-task (crash safety).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Release(self, request, context):
        """Release a lease -> the instance goes idle and is reaped after the idle grace.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Pool snapshot (for debugging / status).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GpudServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Acquire': grpc.unary_unary_rpc_method_handler(
                    servicer.Acquire,
                    request_deserializer=yapper__rpc_dot_gpud__pb2.AcquireRequest.FromString,
                    response_serializer=yapper__rpc_dot_gpud__pb2.Lease.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=yapper__rpc_dot_gpud__pb2.LeaseRef.FromString,
                    response_serializer=yapper__rpc_dot_gpud__pb2.HeartbeatReply.SerializeToString,
            ),
            'Release': grpc.unary_unary_rpc_method_handler(
                    servicer.Release,
                    request_deserializer=yapper__rpc_dot_gpud__pb2.LeaseRef.FromString,
                    response_serializer=yapper__rpc_dot_gpud__pb2.ReleaseReply.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=yapper__rpc_dot_gpud__pb2.StatusRequest.FromString,
                    response_serializer=yapper__rpc_dot_gpud__pb2.StatusReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yapper_rpc.Gpud', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Gpud(object):
    """gpud — the on-demand GPU supervisor. Runs always-on (no model loaded) on the GPU box
    and owns a bounded pool of ASR/TTS model-server subprocesses. A worker leases an
    instance for the duration of one Celery task: gpud launches one on a GPU with free
    vRAM (or hands back a warm idle one), returns its address, and reaps it after an idle
    grace once released. Workers dial the returned `target` directly over gRPC (the model
    traffic never passes through gpud — it's control-plane only).
    """

    @staticmethod
    def Acquire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yapper_rpc.Gpud/Acquire',
            yapper__rpc_dot_gpud__pb2.AcquireRequest.SerializeToString,
            yapper__rpc_dot_gpud__pb2.Lease.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yapper_rpc.Gpud/Heartbeat',
            yapper__rpc_dot_gpud__pb2.LeaseRef.SerializeToString,
            yapper__rpc_dot_gpud__pb2.HeartbeatReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Release(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yapper_rpc.Gpud/Release',
            yapper__rpc_dot_gpud__pb2.LeaseRef.SerializeToString,
            yapper__rpc_dot_gpud__pb2.ReleaseReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yapper_rpc.Gpud/Status',
            yapper__rpc_dot_gpud__pb2.StatusRequest.SerializeToString,
            yapper__rpc_dot_gpud__pb2.StatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
