# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yapper_rpc/gpud.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15yapper_rpc/gpud.proto\x12\nyapper_rpc\"!\n\x0e\x41\x63quireRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"I\n\x05Lease\x12\x10\n\x08lease_id\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\x12\x0f\n\x07service\x18\x03 \x01(\t\x12\r\n\x05ready\x18\x04 \x01(\x08\"\x1c\n\x08LeaseRef\x12\x10\n\x08lease_id\x18\x01 \x01(\t\"\x1c\n\x0eHeartbeatReply\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x1a\n\x0cReleaseReply\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x0f\n\rStatusRequest\"f\n\x0eInstanceStatus\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\x12\x11\n\tgpu_index\x18\x03 \x01(\x05\x12\x0e\n\x06leased\x18\x04 \x01(\x08\x12\x10\n\x08lease_id\x18\x05 \x01(\t\"=\n\tGpuStatus\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0f\n\x07\x66ree_mb\x18\x02 \x01(\x03\x12\x10\n\x08total_mb\x18\x03 \x01(\x03\"a\n\x0bStatusReply\x12-\n\tinstances\x18\x01 \x03(\x0b\x32\x1a.yapper_rpc.InstanceStatus\x12#\n\x04gpus\x18\x02 \x03(\x0b\x32\x15.yapper_rpc.GpuStatus2\xf8\x01\n\x04Gpud\x12\x38\n\x07\x41\x63quire\x12\x1a.yapper_rpc.AcquireRequest\x1a\x11.yapper_rpc.Lease\x12=\n\tHeartbeat\x12\x14.yapper_rpc.LeaseRef\x1a\x1a.yapper_rpc.HeartbeatReply\x12\x39\n\x07Release\x12\x14.yapper_rpc.LeaseRef\x1a\x18.yapper_rpc.ReleaseReply\x12<\n\x06Status\x12\x19.yapper_rpc.StatusRequest\x1a\x17.yapper_rpc.StatusReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yapper_rpc.gpud_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ACQUIREREQUEST']._serialized_start=37
  _globals['_ACQUIREREQUEST']._serialized_end=70
  _globals['_LEASE']._serialized_start=72
  _globals['_LEASE']._serialized_end=145
  _globals['_LEASEREF']._serialized_start=147
  _globals['_LEASEREF']._serialized_end=175
  _globals['_HEARTBEATREPLY']._serialized_start=177
  _globals['_HEARTBEATREPLY']._serialized_end=205
  _globals['_RELEASEREPLY']._serialized_start=207
  _globals['_RELEASEREPLY']._serialized_end=233
  _globals['_STATUSREQUEST']._serialized_start=235
  _globals['_STATUSREQUEST']._serialized_end=250
  _globals['_INSTANCESTATUS']._serialized_start=252
  _globals['_INSTANCESTATUS']._serialized_end=354
  _globals['_GPUSTATUS']._serialized_start=356
  _globals['_GPUSTATUS']._serialized_end=417
  _globals['_STATUSREPLY']._serialized_start=419
  _globals['_STATUSREPLY']._serialized_end=516
  _globals['_GPUD']._serialized_start=519
  _globals['_GPUD']._serialized_end=767
# @@protoc_insertion_point(module_scope)
