# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yapper_rpc/tts.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14yapper_rpc/tts.proto\x12\nyapper_rpc\"a\n\x11SynthesizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04seed\x18\x02 \x01(\x05\x12\r\n\x05speed\x18\x03 \x01(\x01\x12\x0f\n\x07ref_wav\x18\x04 \x01(\t\x12\x10\n\x08ref_text\x18\x05 \x01(\t\"\x1a\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32L\n\x03Tts\x12\x45\n\nSynthesize\x12\x1d.yapper_rpc.SynthesizeRequest\x1a\x16.yapper_rpc.AudioChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yapper_rpc.tts_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNTHESIZEREQUEST']._serialized_start=36
  _globals['_SYNTHESIZEREQUEST']._serialized_end=133
  _globals['_AUDIOCHUNK']._serialized_start=135
  _globals['_AUDIOCHUNK']._serialized_end=161
  _globals['_TTS']._serialized_start=163
  _globals['_TTS']._serialized_end=239
# @@protoc_insertion_point(module_scope)
